/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-05-07 13:58:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class compair_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1698568333846L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696946817737L));
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
    _jspx_dependants.put("/taglib/taglib.jsp", Long.valueOf(1714986046813L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1696946812986L));
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1695567793459L));
    _jspx_dependants.put("jar:file:/D:/demowebbanhang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanHang/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>So sánh</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div id=\"sidebar\" class=\"span3\">\r\n");
      out.write("<div class=\"well well-small\">\r\n");
      out.write("	<ul class=\"nav nav-list\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<li style=\"border: 0\">&nbsp;</li>\r\n");
      out.write("					<li><a class=\"totalInCart\" href=\"cart.html\"><strong>Tổng <span class=\"badge badge-warning pull-right\"\r\n");
      out.write("								style=\"line-height: 18px;\">0$</span>\r\n");
      out.write("						</strong></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			  <div class=\"well well-small alert alert-warning cntr\">\r\n");
      out.write("				  <h2>50% Discount</h2>\r\n");
      out.write("				  <p> \r\n");
      out.write("					 only valid for online order. <br><br><a class=\"defaultBtn\" href=\"#\">Click here </a>\r\n");
      out.write("				  </p>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <div class=\"well well-small\" ><a href=\"#\"><img src=\"assets/img/paypal.jpg\" alt=\"payment method paypal\"></a></div>\r\n");
      out.write("			\r\n");
      out.write("			<a class=\"shopBtn btn-block\" href=\"#\">Upcoming products <br><small>Click to view</small></a>\r\n");
      out.write("			<br>\r\n");
      out.write("			<br>\r\n");
      out.write("			<ul class=\"nav nav-list promowrapper\">\r\n");
      out.write("			<li>\r\n");
      out.write("			  <div class=\"thumbnail\">\r\n");
      out.write("				<a class=\"zoomTool\" href=\"product_details.html\" title=\"add to cart\"><span class=\"icon-search\"></span> QUICK VIEW</a>\r\n");
      out.write("				<img src=\"assets/img/bootstrap-ecommerce-templates.png\" alt=\"bootstrap ecommerce templates\">\r\n");
      out.write("				<div class=\"caption\">\r\n");
      out.write("				  <h4><a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span class=\"pull-right\">$22.00</span></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li style=\"border:0\"> &nbsp;</li>\r\n");
      out.write("			<li>\r\n");
      out.write("			  <div class=\"thumbnail\">\r\n");
      out.write("				<a class=\"zoomTool\" href=\"product_details.html\" title=\"add to cart\"><span class=\"icon-search\"></span> QUICK VIEW</a>\r\n");
      out.write("				<img src=\"assets/img/shopping-cart-template.png\" alt=\"shopping cart template\">\r\n");
      out.write("				<div class=\"caption\">\r\n");
      out.write("				  <h4><a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span class=\"pull-right\">$22.00</span></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li style=\"border:0\"> &nbsp;</li>\r\n");
      out.write("			<li>\r\n");
      out.write("			  <div class=\"thumbnail\">\r\n");
      out.write("				<a class=\"zoomTool\" href=\"product_details.html\" title=\"add to cart\"><span class=\"icon-search\"></span> QUICK VIEW</a>\r\n");
      out.write("				<img src=\"assets/img/bootstrap-template.png\" alt=\"bootstrap template\">\r\n");
      out.write("				<div class=\"caption\">\r\n");
      out.write("				  <h4><a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span class=\"pull-right\">$22.00</span></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</li>\r\n");
      out.write("		  </ul>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"span9\">\r\n");
      out.write("    <ul class=\"breadcrumb\">\r\n");
      out.write("		<li><a href=\"index.html\">Home</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("		<li class=\"active\">Products Compairsition</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("	<div class=\"well well-small\">\r\n");
      out.write("	<h3> Products Compairsition <small class=\"pull-right\"> 2 products are compaired </small></h3>	\r\n");
      out.write("	<hr class=\"soft\"/>\r\n");
      out.write("	\r\n");
      out.write("	<table id=\"compairTbl\" class=\"table table-bordered\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>Features</th>\r\n");
      out.write("                  <th>Product1 name here </th>\r\n");
      out.write("                  <th>Product2 name here</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                  <td>\r\n");
      out.write("					<p class=\"justify\">\r\n");
      out.write("						Nowadays the lingerie industry is one of the most successful business spheres.\r\n");
      out.write("						We always stay in touch with the latest fashion tendencies - that is why our \r\n");
      out.write("						goods are so popular and we have a great number of faithful customers all over the country.\r\n");
      out.write("					</p>\r\n");
      out.write("				<img src=\"assets/img/d.jpg\" alt=\"\"/>\r\n");
      out.write("				<form class=\"form-horizontal qtyFrm\">\r\n");
      out.write("				<h3> $140.00</h3><br/>\r\n");
      out.write("				<div class=\"btn-group\">\r\n");
      out.write("				 <a href=\"product_details.html\" class=\"defaultBtn btn-large\"><span class=\" icon-shopping-cart\"></span> Add to cart</a>\r\n");
      out.write("				 <a href=\"product_details.html\" class=\"shopBtn btn-large\">VIEW</a>\r\n");
      out.write("				 </div>\r\n");
      out.write("				</form>\r\n");
      out.write("				</td>\r\n");
      out.write("                  <td>\r\n");
      out.write("				  <p class=\"justify\">\r\n");
      out.write("					Nowadays the lingerie industry is one of the most successful business spheres.\r\n");
      out.write("					We always stay in touch with the latest fashion tendencies - that is why our \r\n");
      out.write("					goods are so popular and we have a great number of faithful customers all over the country.\r\n");
      out.write("				</p>\r\n");
      out.write("				<img src=\"assets/img/e.jpg\" alt=\"\"/>\r\n");
      out.write("				\r\n");
      out.write("				<form class=\"form-horizontal qtyFrm\">\r\n");
      out.write("				<h3> $140.00</h3>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<div class=\"btn-group\">\r\n");
      out.write("				 <a href=\"product_details.html\" class=\"defaultBtn btn-large\"><span class=\" icon-shopping-cart\"></span> Add to cart</a>\r\n");
      out.write("				 <a href=\"product_details.html\" class=\"shopBtn btn-large\">VIEW</a>\r\n");
      out.write("				 </div>\r\n");
      out.write("				</form>\r\n");
      out.write("				  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>Height</td>\r\n");
      out.write("                  <td>5\"</td>\r\n");
      out.write("                  <td>15\"</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>Deepth</td>\r\n");
      out.write("                  <td>5\"</td>\r\n");
      out.write("                  <td>5\"</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("                  <td>Size</td>\r\n");
      out.write("                  <td>XXL</td>\r\n");
      out.write("                  <td>XL</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("                  <td>Width</td>\r\n");
      out.write("                  <td>6.5\"</td>\r\n");
      out.write("                  <td>6\"</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("                  <td>Weight</td>\r\n");
      out.write("                  <td>0.5kg</td>\r\n");
      out.write("                  <td>0.8kg</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>		\r\n");
      out.write("	<div class=\"alignR\"><a href=\"products.html\" class=\"shopBtn btn-large\">Back to Products Page</a></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/compair.jsp(15,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/user/compair.jsp(15,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/compair.jsp(15,5) '${category}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${category}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<li><a href=\"products.html\"><span class=\"icon-chevron-right\"></span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
